// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in /afs/cern.ch/work/k/kmcdermo/private/dispho/CMSSW_9_4_4/src/Timing/TimingAnalyzer/dispho_work/macros/common/Common.hh;
#pragma link C++ defined_in "/afs/cern.ch/work/k/kmcdermo/private/dispho/CMSSW_9_4_4/src/Timing/TimingAnalyzer/dispho_work/macros/common/Common.cpp";

#endif
